name: Deploy React App to Server

on:
  push:
    branches:
      - anjana

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies and Build
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_API: ${{ secrets.VITE_API }}
        run: |
          npm ci
          npm run build

      - name: Rename dist to loyalty-frontend
        run: mv ./dist ./loyalty-frontend

      - name: Clean Temporary Directory on Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            rm -rf ~/deploy-temp
            mkdir ~/deploy-temp

      - name: Copy Files to Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: ./loyalty-frontend/
          target: ~/deploy-temp/

      - name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            sudo rm -rf /var/www/html/loyalty-frontend
            sudo mv ~/deploy-temp/* /var/www/html/
            sudo rm -rf ~/deploy-temp
            sudo rm -rf /var/cache/nginx/*
            sudo systemctl restart nginx
