name: Deploy React App to  prod-Server

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: [self-hosted, prod]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies and Build
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_API: ${{ secrets.VITE_API_PROD }}
        run: |
          npm ci
          npm run build

      - name: Rename dist to loyalty-frontend
        run: mv ./dist ./loyalty-frontend

      - name: Save staging IP locally
        run: echo "${{ secrets.SERVER_HOST }}" > /home/loyalty/staging_host_ip.txt


      - name: Clean Temporary Directory on Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST_PROD }}
          username: ${{ secrets.SERVER_USER_PROD }}
          password: ${{ secrets.SERVER_PASSWORD_PROD }}
          script: |
            rm -rf ~/deploy-temp
            mkdir ~/deploy-temp

      - name: Copy Files to Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST_PROD }}
          username: ${{ secrets.SERVER_USER_PROD }}
          password: ${{ secrets.SERVER_PASSWORD_PROD }}
          source: ./loyalty-frontend/
          target: ~/deploy-temp/loyalty-frontend/

      - name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST_PROD }}
          username: ${{ secrets.SERVER_USER_PROD }}
          password: ${{ secrets.SERVER_PASSWORD_PROD }}
          script: |
            echo "${{ secrets.SERVER_PASSWORD_PROD }}" | sudo -S rm -rf /var/www/html/loyalty-frontend
            echo "${{ secrets.SERVER_PASSWORD_PROD }}" | sudo -S mv ~/deploy-temp/loyalty-frontend /var/www/html/
            echo "${{ secrets.SERVER_PASSWORD_PROD }}" | sudo -S rm -rf ~/deploy-temp
            echo "${{ secrets.SERVER_PASSWORD_PROD }}" | sudo -S rm -rf /var/cache/nginx/*
            echo "${{ secrets.SERVER_PASSWORD_PROD }}" | sudo -S systemctl restart nginx
